name: Check Nightly Workflow

on:
  schedule:
    - cron: '*/10 * * * *' # Alle 10 Minuten prüfen

jobs:
  check-nightly:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Nightly Workflow Status
      id: check
      run: |
        NIGHTLY_RUN=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/<quell-benutzername>/<quell-repository>/actions/workflows/nightly.yml/runs?status=success&per_page=1" \
        | jq -r '.workflow_runs[0]')
        
        NIGHTLY_RUN_ID=$(echo $NIGHTLY_RUN | jq -r '.id')
        NIGHTLY_RUN_CONCLUSION=$(echo $NIGHTLY_RUN | jq -r '.conclusion')

        if [ "$NIGHTLY_RUN_CONCLUSION" == "success" ]; then
          echo "Nightly workflow succeeded. Run ID: $NIGHTLY_RUN_ID"
          echo "::set-output name=nightly_run_id::$NIGHTLY_RUN_ID"
        else
          echo "Nightly workflow not succeeded or no recent run found."
          echo "::set-output name=nightly_run_id::null"
        fi

    - name: Trigger own workflow if Nightly succeeded and ID not used
      if: steps.check.outputs.nightly_run_id != 'null'
      run: |
        NIGHTLY_RUN_ID=${{ steps.check.outputs.nightly_run_id }}
        echo $NIGHTLY_RUN_ID >> .github/nightly_run_ids.txt
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"event_type":"nightly_completed", "client_payload": {"nightly_run_id": "'$NIGHTLY_RUN_ID'"}}' \
        https://api.github.com/repos/<dein-benutzername>/<dein-repository>/dispatches
